// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gkfamyxpktfodfjrpckj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdrZmFteXhwa3Rmb2RmanJwY2tqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTExNzI3MDYsImV4cCI6MjA2Njc0ODcwNn0.LI6JKL1XIFxLo87mL1bJI3LE2B_lxFExY-mjA45UHg8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);